name: homelab-gateway

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
        - subnet: 2001:db8::/64
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: eth0
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1
        - subnet: fdac::/64
          gateway: fdac::1

include:
  - compose/traefik.yml
  # - compose/oauth.yml
  - compose/authentik.yml
  - compose/uptime-kuma.yml
  - compose/portainer.yml
  - compose/traefik-cert-dumper.yml
  - compose/adguard-home.yml
  - compose/mosdns.yml
  - compose/homarr.yml
  # - compose/natter.yml
