name: homelab-gateway

networks:
  default:
    driver: bridge
  dns_nst:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.31.0/24
          gateway: 192.168.31.1

include:
  - compose/traefik.yml
  # - compose/oauth.yml
  - compose/authentik.yml
  - compose/uptime-kuma.yml
  - compose/portainer.yml
  - compose/traefik-cert-dumper.yml
  - compose/adguard-home.yml
  - compose/mosdns.yml
