# global:
#   checkNewVersion: true
#   sendAnonymousUsage: false

# serversTransport:
#   insecureSkipVerify: true

# entryPoints:
#   web:
#     address: ":80"
#     http:
#       redirections:
#         entryPoint:
#           to: websecure
#           scheme: https
#   websecure:
#     address: ":443"
#     http:
#       tls:
#         certResolver: letsencrypt
#         domains:
#           - main: "*.internal.ryuyb.com"
#             sans: "internal.ryuyb.com"

# providers:
#   docker:
#     exposedByDefault: false
#   file:
#     directory: "/traefik/dynamic_conf"
#     watch: true

# api:
#   insecure: false
#   dashboard: true
#   disableDashboardAd: true

# ping: {}

# log:
#   level: DEBUG
#   filePath: "/traefik/logs/traefik.log"

# accesslog:
#   addInternals: true
#   filepath: /traefik/logs/access.log
#   fields:
#     names:
#       StartUTC: drop
#     headers:
#       names:
#         Content-Type: keep
#         Referer: keep
#         User-Agent: keep

# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: "letsencrypt@internal.ryuyb.com"
#       storage: /traefik/letsencrypt/acme.json
#       dnsChallenge:
#         provider: cloudflare
