services:
  mosdns:
    image: irinesistiana/mosdns:latest
    container_name: mosdns
    restart: unless-stopped
    volumes:
      - ${MOUNT_PATH}/config/mosdns:/etc/mosdns
    networks:
      default:
      macvlan_net:
        ipv4_address: 172.16.1.3
        ipv6_address: fdac::3
