services:
  mosdns:
    image: irinesistiana/mosdns:latest
    container_name: mosdns
    restart: unless-stopped
    volumes:
      - ${MOUNT_PATH}/config/mosdns:/etc/mosdns
    networks:
      default:
      dns_nst:
        ipv4_address: 172.20.0.2
      ipv6_net:
