services:
  mosdns:
    image: irinesistiana/mosdns:latest
    container_name: mosdns
    restart: unless-stopped
    volumes:
      - ${MOUNT_PATH}/config/mosdns:/etc/mosdns
    ports:
      - 53:53/udp
      - 53:53/tcp
    networks:
      macvlan_net:
        ipv4_address: 192.168.31.37
