services:
  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:v2.8.3
    container_name: traefik-certs-dumper
    restart: unless-stopped
    entrypoint: sh -c '
      apk add jq
      ; while ! [ -e /data/acme.json ]
      || ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ]; do
      sleep 1
      ; done
      && traefik-certs-dumper file --version v2 --watch
      --domain-subdir --crt-ext=.pem --key-ext=.pem
      --crt-name=fullchain --key-name=privkey
      --source /data/acme.json --dest /result'
    volumes:
      - ${MOUNT_PATH}/appdata/traefik/letsencrypt:/data
      - ${MOUNT_PATH}/appdata/certs:/result
