services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ${MOUNT_PATH}/appdata/uptime-kuma:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`kuma.${DNS_DOMAIN}`)"
      - "traefik.http.routers.uptime-kuma.middlewares=chain-oauth@file"
      - "traefik.http.routers.uptime-kuma.service=uptime-kuma-svc"
      - "traefik.http.services.uptime-kuma-svc.loadbalancer.server.port=3001"
